name: Feature Request
description: Suggest a new feature or enhancement for Crush
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please help us understand your use case and the value this feature would provide.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it enable?
      placeholder: |
        Example: I'm frustrated when I need to compress files with different algorithms for different file types. Currently, I have to run Crush multiple times with different flags, which is tedious and error-prone.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: |
        Example: Add support for a configuration file (.crushrc) that allows defining compression rules based on file patterns:
        ```yaml
        rules:
          - pattern: "*.txt"
            algorithm: gzip
            level: 9
          - pattern: "*.log"
            algorithm: lz4
            level: 1
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: |
        Example: I could write a shell script to handle this, but a built-in solution would be more robust and easier to maintain.
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Are you willing to contribute this feature?
      description: We welcome contributions! Let us know if you'd like to implement this yourself.
      options:
        - "Yes, I'd like to implement this"
        - "I can help with testing/review"
        - "No, just suggesting"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or examples about the feature request here
    validations:
      required: false
