[package]
name = "crush-gpu-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
crush-gpu = { path = ".." }

[[bin]]
name = "fuzz_format"
path = "fuzz_targets/fuzz_format.rs"
doc = false

[[bin]]
name = "fuzz_decompress"
path = "fuzz_targets/fuzz_decompress.rs"
doc = false

[workspace]
